Update OpenConnectionFromInterfaces:
bmc-toolbox/bmclib pull request #215
Opened 2021-03-22 16:13 UTC by jacobweinstock

Currently, if an implementation that opens a stateful session in its `Opener` implementation fails when open is called and then has a method called, for example, `PowerStateGet`, that needs to use the session info, we will get a panic.

This code updates the `OpenConnectionFromInterfaces` to remove any provider implementation that fails to open successfully. We do this by returning a new `registrar.Drivers` from the Open method in `client.go`.

2021-03-24 20:56 UTC, jacobweinstock commented
Hey @joelrebel, this one is ready for you whenever you have a moment. Thanks!

2021-03-25 19:26 UTC, joelrebel requested changes

2021-03-25 19:35 UTC, jacobweinstock commented on bmc/connection_test.go
> +				t.Log(ok)
ah yes, thanks. will update

2021-03-25 19:38 UTC, jacobweinstock commented on bmc/power.go
>  			if elem.powerSetter != nil {
I like it, will update. thanks!

2021-03-25 19:59 UTC, jacobweinstock commented on bmc/power.go
>  			if elem.powerSetter != nil {
updated

2021-03-25 19:59 UTC, jacobweinstock commented on bmc/connection_test.go
> +				t.Log(ok)
updated

2021-03-25 20:25 UTC, joelrebel approved these changes

2021-03-25 20:25 UTC, joelrebel commented
LGTM, thanks for this!

2021-03-25 20:29 UTC, merged