Connection timeouts
bmc-toolbox/bmclib pull request #310
Opened 2023-03-01 14:12 UTC by joelrebel

## What does this PR implement/change/remove?

Wraps the Intel AMT provider connection setup to return on context deadline.

Adds a connection timeout parameter for opening connection,

As of now, a user may choose to pass in a context deadline into the bmclib client, which
is shared between all the [bmclib providers](https://github.com/bmc-toolbox/bmclib/blob/main/client.go#L115) that is - when creating an a new connection/session on a BMC.

The shared timeout value entails that a single provider can attempt to connect for the the whole timeout deadline, and so leaving the other providers (which may be the successful ones) with much lesser time to connect and carry out their operation.

The `WithConnectTimeout()` client option sets the timeout when connecting to a BMC to create a new session.
When not defined the deadline value passed in (if any) through the context applies.

This timeout value will best work when its lesser than the passed in context deadline value.

### Checklist
- [ ] Tests added
- [ ] Similar commits squashed

### The HW vendor this change applies to (if applicable)
 - Intel AMT

### What version of tooling - vendor specific or opensource does this change depend on (if applicable)

## Description for changelog/release notes

```
```

2023-03-01 14:45 UTC, mmlb approved these changes
lgtm

2023-03-01 16:23 UTC, joelrebel commented
@jacobweinstock let me know if you have any thoughts here.

2023-03-01 16:25 UTC, jacobweinstock commented
> @jacobweinstock let me know if you have any thoughts here.

Hey @joelrebel, thanks for tagging me. Looking now.

2023-03-02 18:45 UTC, jacobweinstock requested changes
Thanks for this @joelrebel. If i understand correctly, this doesnt solve the challenge of a single provider taking the total timeout and not leaving time for other providers to be tried. is that correct? It feels like we might want to propagate the creation of the ctx with timeout in the interface method [here](https://github.com/bmc-toolbox/bmclib/blob/196bcaa650c2b5898205ec01f15936dd59f0fffb/bmc/connection.go#L47). this way each provider is given the same duration. thought?

2023-03-06 19:01 UTC, joelrebel commented on providers/intelamt/intelamt.go
> +		c.client, err = amt.NewClient(conn)
sounds right, go for it.

2023-03-06 19:04 UTC, joelrebel commented on client.go
> +// This timeout value will take effect when its lesser than the passed in context deadline value.
> Thanks for this @joelrebel. If i understand correctly, this doesnt solve the challenge of a single provider taking the total timeout and not leaving time for other providers to be tried. is that correct? 
Yeah, thats correct.

It feels like we might want to propagate the creation of the ctx with timeout in the interface method [here](https://github.com/bmc-toolbox/bmclib/blob/196bcaa650c2b5898205ec01f15936dd59f0fffb/bmc/connection.go#L47). this way each provider is given the same duration. thought?

That sounds like a better approach, I'll give that a try, thanks!

2023-03-07 16:37 UTC, joelrebel commented on client.go
> +// This timeout value will take effect when its lesser than the passed in context deadline value.
updated in [8982ae5](https://github.com/bmc-toolbox/bmclib/pull/310/commits/8982ae5194422dc60a10a93855d5374b460e3b79)

2023-03-07 16:39 UTC, joelrebel commented
@jacobweinstock the latest changes pass the connection timeout as you suggested,
for the AMT changes, should I revert what I have in this PR?

2023-03-08 00:30 UTC, jacobweinstock commented on client.go
> +// WithConnectTimeout sets the timeout when connecting to a BMC to create a new session.
You would mind adding to this that this the same timeout used for each provider?

2023-03-08 00:32 UTC, jacobweinstock commented
> @jacobweinstock the latest changes pass the connection timeout as you suggested, for the AMT changes, should I revert what I have in this PR?

Hey @joelrebel. Thanks, this looks good. Yeah, if you don't mind reverting the AMT changes I've got a PR ready to follow up with the library changes.

2023-03-08 20:44 UTC, joelrebel commented
@jacobweinstock, I've reverted intelAMT changes in [a72d5d6](https://github.com/bmc-toolbox/bmclib/pull/310/commits/a72d5d64cfccd7bc86cb0746e8852bc4f0f1beda)

2023-03-08 21:14 UTC, merged