Move methods under the redfishwrapper for reuse
bmc-toolbox/bmclib pull request #369
Opened 2023-11-27 08:46 UTC by joelrebel

## What does this PR implement/change/remove?

- Moves the Inventory, Power*, GetBiosConfiguration methods under the redfishwrapper package for re-use by other providers.
- A few fixes for the bmc/firmware interface methods - to collect errors in the client metadata obj.

This is to allow each vendor/OEM provider to re-use and extend these methods.

### Checklist
- [ ] Tests added
- [X] Similar commits squashed

2023-11-27 19:10 UTC, coffeefreak101 approved these changes

2023-11-28 07:27 UTC, ofaurax requested changes
All OK but test and lint fail

2023-11-28 09:28 UTC, joelrebel commented
> All OK but test and lint fail

@ofaurax this is 1/4 PR, the 4th PR https://github.com/bmc-toolbox/bmclib/pull/372 when merged will clear tests and linting

2023-11-29 09:29 UTC, ofaurax approved these changes
Lots of changes!

2023-11-29 09:32 UTC, merged